#
version: '3'
services:
  redis:
    image: ${REDIS_NAME}
    command: ${REDIS_COMMAND}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    container_name: ${REDIS_NAME}_dev
  rabbitmq:
    image: ${RABBITMQ_NAME}
    ports:
      - ${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_ADMIN_PORT}:${RABBITMQ_ADMIN_PORT}
    container_name: ${RABBITMQ_NAME}_dev
  neo4j:
    image: ${NEO4J_NAME}
    ports:
      - ${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}
      - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}
    container_name: ${NEO4J_NAME}_dev
    environment:
      - NEO4J_AUTH=neo4j/secret
  mongo:
    image: ${MONGO_NAME}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    container_name: ${MONGO_NAME}_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test
  mysql:
    image: ${MYSQL_NAME}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    container_name: ${MYSQL_NAME}_dev
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_mysql
      - MYSQL_ROOT_PASSWORD=root