#
version: '3'
services:
  redis:
    image: ${REDIS_NAME}
    command: ${REDIS_COMMAND}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    container_name: ${REDIS_NAME}
  rabbitmq:
    image: ${RABBITMQ_NAME}
    ports:
      - ${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_ADMIN_PORT}:${RABBITMQ_ADMIN_PORT}
    container_name: ${RABBITMQ_NAME}
  neo4j:
    image: ${NEO4J_NAME}
    ports:
      - ${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}
      - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}
    container_name: ${NEO4J_NAME}
    environment:
      - NEO4J_AUTH=neo4j/secret