spring:
  application:
    name: eureka-client

server:
  port: 8087

#  actuator
management:
  server:
    port: 9087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka/