# spring
spring:
  application:
    name: eureka-client

# port
server:
  port: 8086

#  actuator
management:
  server:
    port: 9088

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/