server:
  port: 8084

#  actuator
management:
  server:
    port: 9084

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config