# spring
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config

# port
server:
  port: 8084

#  actuator
management:
  server:
    port: 9086