# port
server:
  port: 8081

#  log
logging:
  config: classpath:logback.xml

#  actuator
management:
  server:
    port: 9081

# spring
spring:
  application:
    name: spring-application
  data:
    neo4j:
      password: secret
      username: neo4j
    mongodb:
      uri: mongodb://root:123456@localhost:27017/test?authSource=admin
  neo4j:
    uri: bolt://localhost:7687

# consuming api
consuming:
  url: https://quoters.apps.pcfone.io/api/random

# upload file storage path
storage:
  location: upload-dir

# multi module
service:
  message: Hello, application

# eureka
eureka:
  instance:
    hostname: eureka-consume
  client:
    serviceUrl:
      defaultZone: http://localhost:8086/eureka

# eureka provider
provider:
  client:
    name: eureka-client
    url: service
