server:
  port: 8085
logging:
  config: classpath:logback.xml
management:
  server:
    port: 9001
    address: 127.0.0.1
spring:
  data:
    neo4j:
      password: secret
      username: neo4j
  neo4j:
    uri: bolt://localhost:7687