#
version: '3'
services:
  web:
    build: .
    image: ${MYAPP_NAME}
    ports:
      - ${MYAPP_PORT}:${MYAPP_PORT}
    container_name: ${MYAPP_NAME}
    volumes:
    - ../target/${MYAPP_JAR}.jar:/tmp/${MYAPP_JAR}.jar
#    depends_on:
#      - redis
#  redis:
#    image: ${REDIS_NAME}
#    command: ${REDIS_COMMAND}
#    ports:
#      - ${REDIS_PORT}:${REDIS_PORT}
#    container_name: ${REDIS_NAME}
#  rabbitmq:
#    image: ${RABBITMQ_NAME}
#    ports:
#      - ${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}
#      - ${RABBITMQ_ADMIN_PORT}:${RABBITMQ_ADMIN_PORT}
#    container_name: ${RABBITMQ_NAME}
#  neo4j:
#    image: ${NEO4J_NAME}
#    ports:
#      - ${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}
#      - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}
#    container_name: ${NEO4J_NAME}