# spring
spring:
  application:
    name: spring-cloud
  config:
    import: optional:configserver:http://localhost:8084/

# port
server:
  port: 8087

#  actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9087

# eureka
eureka:
  instance:
    hostname: eureka-consume
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka

# eureka provider
provider:
  client:
    name: eureka-client
    url: service

#  log
logging:
  config: classpath:logback.xml