#
version: '3'
services:
  web:
    build: ../${WEB_JAR}
    image: ${WEB_IMAGE}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${WEB_ACT_PORT}:${WEB_ACT_PORT}
    container_name: ${WEB_IMAGE}
    volumes:
    - ../${WEB_JAR}/target/${WEB_JAR}.jar:/tmp/${WEB_JAR}.jar
  db:
    build: ../${DATA_BASE_JAR}
    image: ${DB_IMAGE}
    ports:
      - ${DATA_BASE_PORT}:${DATA_BASE_PORT}
    container_name: ${DB_IMAGE}
    volumes:
      - ../${DATA_BASE_JAR}/target/${DATA_BASE_JAR}.jar:/tmp/${DATA_BASE_JAR}.jar
    depends_on:
      - neo4j
      - mongo
  message:
    build: ../${MESSAGE_JAR}
    image: ${MESSAGE_IMAGE}
    ports:
      - ${MESSAGE_PORT}:${MESSAGE_PORT}
    container_name: ${MESSAGE_IMAGE}
    volumes:
      - ../${MESSAGE_JAR}/target/${MESSAGE_JAR}.jar:/tmp/${MESSAGE_JAR}.jar
    depends_on:
      - redis
      - rabbitmq
  config:
    build: ../${CONFIG_SERVICE_JAR}
    image: ${CONFIG_IMAGE}
    ports:
      - ${CONFIG_SERVICE_PORT}:${CONFIG_SERVICE_PORT}
    container_name: ${CONFIG_IMAGE}
    volumes:
      - ../${CONFIG_SERVICE_JAR}/target/${CONFIG_SERVICE_JAR}.jar:/tmp/${CONFIG_SERVICE_JAR}.jar
  cloud:
    build: ../${CLOUD_JAR}
    image: ${CLOUD_IMAGE}
    ports:
      - ${EUREKA_SERVICE_PORT}:${EUREKA_SERVICE_PORT}
      - ${EUREKA_CLIENT_PORT}:${EUREKA_CLIENT_PORT}
      - ${CLOUD_PORT}:${CLOUD_PORT}
      - ${CLOUD_ACT_PORT}:${CLOUD_ACT_PORT}
    container_name: ${CLOUD_IMAGE}
    volumes:
      - ../${EUREKA_SERVICE_JAR}/target/${EUREKA_SERVICE_JAR}.jar:/tmp/${EUREKA_SERVICE_JAR}.jar
      - ../${EUREKA_CLIENT_JAR}/target/${EUREKA_CLIENT_JAR}.jar:/tmp/${EUREKA_CLIENT_JAR}.jar
      - ../${CLOUD_JAR}/target/${CLOUD_JAR}.jar:/tmp/${CLOUD_JAR}.jar
    depends_on:
      - config
  sql:
    build: ../${SQL_JAR}
    image: ${SQL_IMAGE}
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    container_name: ${SQL_IMAGE}
    volumes:
      - ../${SQL_JAR}/target/${SQL_JAR}.jar:/tmp/${SQL_JAR}.jar
    depends_on:
      - mysql
  redis:
    image: ${REDIS_NAME}
    command: ${REDIS_COMMAND}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    container_name: ${REDIS_NAME}
  rabbitmq:
    image: ${RABBITMQ_NAME}
    ports:
      - ${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_ADMIN_PORT}:${RABBITMQ_ADMIN_PORT}
    container_name: ${RABBITMQ_NAME}
  neo4j:
    image: ${NEO4J_NAME}
    ports:
      - ${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}
      - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}
    container_name: ${NEO4J_NAME}
    environment:
      - NEO4J_AUTH=neo4j/secret
  mongo:
    image: ${MONGO_NAME}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    container_name: ${MONGO_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test
  mysql:
    image: ${MYSQL_NAME}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    container_name: ${MYSQL_NAME}
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_mysql
      - MYSQL_ROOT_PASSWORD=root