#
version: '3'
services:
  db:
    build: ../${DATA_BASE_JAR}
    image: ${DB_IMAGE}
    ports:
      - ${DATA_BASE_PORT}:${DATA_BASE_PORT}
    container_name: ${DB_IMAGE}
    volumes:
    - ../${DATA_BASE_JAR}/target/${DATA_BASE_JAR}.jar:/tmp/${DATA_BASE_JAR}.jar
    depends_on:
      - neo4j
      - mongo
  neo4j:
    image: ${NEO4J_NAME}
    ports:
      - ${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}
      - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}
    container_name: ${NEO4J_NAME}
    environment:
      - NEO4J_AUTH=neo4j/secret
  mongo:
    image: ${MONGO_NAME}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    container_name: ${MONGO_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test