#
version: '3'
services:
  message:
    build: ../${MESSAGE_JAR}
    image: ${MESSAGE_IMAGE}
    ports:
      - ${MESSAGE_PORT}:${MESSAGE_PORT}
    container_name: ${MESSAGE_IMAGE}
    volumes:
    - ../${MESSAGE_JAR}/target/${MESSAGE_JAR}.jar:/tmp/${MESSAGE_JAR}.jar
    depends_on:
      - redis
      - rabbitmq
  redis:
    image: ${REDIS_NAME}
    command: ${REDIS_COMMAND}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    container_name: ${REDIS_NAME}
  rabbitmq:
    image: ${RABBITMQ_NAME}
    ports:
      - ${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_ADMIN_PORT}:${RABBITMQ_ADMIN_PORT}
    container_name: ${RABBITMQ_NAME}