#
version: '3'
services:
  gate:
    build: ../${GATE_JAR}
    image: ${GATE_IMAGE}
    ports:
      - ${GATE_PORT}:${GATE_PORT}
    container_name: ${GATE_IMAGE}
    volumes:
      - ../${GATE_JAR}/target/${GATE_JAR}.jar:/tmp/${GATE_JAR}.jar