spring:
  application:
    name: client
  config:
    import: optional:configserver:http://localhost:8084/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9085
server:
  port: 8085