#
version: '3'
services:
  web:
    build: ../${WEB_JAR}
    image: ${WEB_IMAGE}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${WEB_ACT_PORT}:${WEB_ACT_PORT}
    container_name: ${WEB_IMAGE}
    volumes:
    - ../${WEB_JAR}/target/${WEB_JAR}.jar:/tmp/${WEB_JAR}.jar